export const TOTAL_NUMBER_OF_CARD_PAIRS = 6;

export const CARD_NUMBER_RANGE_FROM = 1;

export const CARD_NUMBER_RANGE_TO = 100;

export const FLIP_BACK_ANIMATION_DURATION = 1000;

export const FLIP_ANIMATION_DURATION = 300;
